### ISSUE TITLE
prevent user from playing mutiple videos on same page at same time

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-youtube#2]
have done most of the work in ken14242 already, just need to port that code over

**Comment by oliverfoster** [comment]
Really need a global "media:stop" event. Got audio + video to contend with.

**Comment by moloko** [comment]
fixed in a7f7897a9d55899ad81170fb6cacfc60954d55f6

**Comment by moloko** [comment]
@oliverfoster plugin now implements `media:stop`

**Comment by oliverfoster** [comment]
:+1:
