### ISSUE TITLE
properties.schema - Source Url Input field is not displaying in authoring tool

### ISSUE THREAD

**Issue by mike-st** [cgkineo/adapt-youtube#5]
Hey Matt
Sorry to bug you once again. I Found another issue with the properties.schema. The Source Url Input field is not displaying in authoring tool. Therefore the course is erroring out on preview as it thinks there is no youtube url and I can't input the youtube url location into the component. Here is an image to help explain...
![youtube-error](https://cloud.githubusercontent.com/assets/10455453/12098111/0a08f862-b2ee-11e5-8dd2-cfba53f1cd2d.jpg)

**Comment by moloko** [comment]
argh sorry @mike-st, poor copy-pasting on my part... will be fixed very shortly!

**Comment by mike-st** [comment]
Thanks again Matt. You Rock!
